// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package org.damazio.notifier.protocol;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.damazio.notifier.protocol.Event)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional int64 source_device_id = 1;</code>
     *
     * <pre>
     * The device that generated this event.
     * If unset then the event was generated by the local device.
     * This field will always be set when the event is being sent between devices.
     * </pre>
     */
    boolean hasSourceDeviceId();
    /**
     * <code>optional int64 source_device_id = 1;</code>
     *
     * <pre>
     * The device that generated this event.
     * If unset then the event was generated by the local device.
     * This field will always be set when the event is being sent between devices.
     * </pre>
     */
    long getSourceDeviceId();

    /**
     * <code>repeated int64 target_device_id = 2;</code>
     *
     * <pre>
     * Zero or more devices that this event is targeted to.
     * If none specified, then it's meant for all devices that receive it.
     * </pre>
     */
    java.util.List<java.lang.Long> getTargetDeviceIdList();
    /**
     * <code>repeated int64 target_device_id = 2;</code>
     *
     * <pre>
     * Zero or more devices that this event is targeted to.
     * If none specified, then it's meant for all devices that receive it.
     * </pre>
     */
    int getTargetDeviceIdCount();
    /**
     * <code>repeated int64 target_device_id = 2;</code>
     *
     * <pre>
     * Zero or more devices that this event is targeted to.
     * If none specified, then it's meant for all devices that receive it.
     * </pre>
     */
    long getTargetDeviceId(int index);

    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     * When the event happened, in milliseconds since the epoch, UTC.
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     * When the event happened, in milliseconds since the epoch, UTC.
     * </pre>
     */
    long getTimestamp();

    /**
     * <code>required .org.damazio.notifier.protocol.Event.Type type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>required .org.damazio.notifier.protocol.Event.Type type = 4;</code>
     */
    org.damazio.notifier.protocol.Common.Event.Type getType();

    /**
     * <code>optional bytes payload = 5;</code>
     *
     * <pre>
     * Payload is the type-dependent encoded protocol buffer payload.
     * A missing payload happens if no details were available about the event.
     * </pre>
     */
    boolean hasPayload();
    /**
     * <code>optional bytes payload = 5;</code>
     *
     * <pre>
     * Payload is the type-dependent encoded protocol buffer payload.
     * A missing payload happens if no details were available about the event.
     * </pre>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code org.damazio.notifier.protocol.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:org.damazio.notifier.protocol.Event)
      EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Event(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }

    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sourceDeviceId_ = input.readInt64();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                targetDeviceId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              targetDeviceId_.add(input.readInt64());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                targetDeviceId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                targetDeviceId_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              org.damazio.notifier.protocol.Common.Event.Type value = org.damazio.notifier.protocol.Common.Event.Type.valueOf(rawValue);
              if (value == null) {
                unknownFieldsCodedOutput.writeRawVarint32(tag);
                unknownFieldsCodedOutput.writeRawVarint32(rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          targetDeviceId_ = java.util.Collections.unmodifiableList(targetDeviceId_);
        }
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Event> PARSER =
        new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.damazio.notifier.protocol.Event.Type}
     *
     * <pre>
     * The type of event.
     * </pre>
     */
    public enum Type
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>NOTIFICATION_RING = 1;</code>
       */
      NOTIFICATION_RING(0, 1),
      /**
       * <code>NOTIFICATION_MISSED_CALL = 2;</code>
       */
      NOTIFICATION_MISSED_CALL(1, 2),
      /**
       * <code>NOTIFICATION_VOICEMAIL = 3;</code>
       */
      NOTIFICATION_VOICEMAIL(2, 3),
      /**
       * <code>NOTIFICATION_SMS = 4;</code>
       */
      NOTIFICATION_SMS(3, 4),
      /**
       * <code>NOTIFICATION_MMS = 5;</code>
       */
      NOTIFICATION_MMS(4, 5),
      /**
       * <code>NOTIFICATION_BATTERY = 6;</code>
       */
      NOTIFICATION_BATTERY(5, 6),
      /**
       * <code>NOTIFICATION_THIRD_PARTY = 7;</code>
       */
      NOTIFICATION_THIRD_PARTY(6, 7),
      /**
       * <code>NOTIFICATION_MASK = 15;</code>
       *
       * <pre>
       * Bits 0-3
       * </pre>
       */
      NOTIFICATION_MASK(7, 15),
      /**
       * <code>COMMAND_CALL = 16;</code>
       */
      COMMAND_CALL(8, 16),
      /**
       * <code>COMMAND_HANGUP = 17;</code>
       */
      COMMAND_HANGUP(9, 17),
      /**
       * <code>COMMAND_SMS = 18;</code>
       */
      COMMAND_SMS(10, 18),
      /**
       * <code>COMMAND_THIRD_PARTY = 19;</code>
       */
      COMMAND_THIRD_PARTY(11, 19),
      /**
       * <code>COMMAND_MASK = 240;</code>
       *
       * <pre>
       * Bits 4-7
       * </pre>
       */
      COMMAND_MASK(12, 240),
      ;

      /**
       * <code>NOTIFICATION_RING = 1;</code>
       */
      public static final int NOTIFICATION_RING_VALUE = 1;
      /**
       * <code>NOTIFICATION_MISSED_CALL = 2;</code>
       */
      public static final int NOTIFICATION_MISSED_CALL_VALUE = 2;
      /**
       * <code>NOTIFICATION_VOICEMAIL = 3;</code>
       */
      public static final int NOTIFICATION_VOICEMAIL_VALUE = 3;
      /**
       * <code>NOTIFICATION_SMS = 4;</code>
       */
      public static final int NOTIFICATION_SMS_VALUE = 4;
      /**
       * <code>NOTIFICATION_MMS = 5;</code>
       */
      public static final int NOTIFICATION_MMS_VALUE = 5;
      /**
       * <code>NOTIFICATION_BATTERY = 6;</code>
       */
      public static final int NOTIFICATION_BATTERY_VALUE = 6;
      /**
       * <code>NOTIFICATION_THIRD_PARTY = 7;</code>
       */
      public static final int NOTIFICATION_THIRD_PARTY_VALUE = 7;
      /**
       * <code>NOTIFICATION_MASK = 15;</code>
       *
       * <pre>
       * Bits 0-3
       * </pre>
       */
      public static final int NOTIFICATION_MASK_VALUE = 15;
      /**
       * <code>COMMAND_CALL = 16;</code>
       */
      public static final int COMMAND_CALL_VALUE = 16;
      /**
       * <code>COMMAND_HANGUP = 17;</code>
       */
      public static final int COMMAND_HANGUP_VALUE = 17;
      /**
       * <code>COMMAND_SMS = 18;</code>
       */
      public static final int COMMAND_SMS_VALUE = 18;
      /**
       * <code>COMMAND_THIRD_PARTY = 19;</code>
       */
      public static final int COMMAND_THIRD_PARTY_VALUE = 19;
      /**
       * <code>COMMAND_MASK = 240;</code>
       *
       * <pre>
       * Bits 4-7
       * </pre>
       */
      public static final int COMMAND_MASK_VALUE = 240;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return NOTIFICATION_RING;
          case 2: return NOTIFICATION_MISSED_CALL;
          case 3: return NOTIFICATION_VOICEMAIL;
          case 4: return NOTIFICATION_SMS;
          case 5: return NOTIFICATION_MMS;
          case 6: return NOTIFICATION_BATTERY;
          case 7: return NOTIFICATION_THIRD_PARTY;
          case 15: return NOTIFICATION_MASK;
          case 16: return COMMAND_CALL;
          case 17: return COMMAND_HANGUP;
          case 18: return COMMAND_SMS;
          case 19: return COMMAND_THIRD_PARTY;
          case 240: return COMMAND_MASK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      private final int value;

      private Type(int index, int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.damazio.notifier.protocol.Event.Type)
    }

    private int bitField0_;
    public static final int SOURCE_DEVICE_ID_FIELD_NUMBER = 1;
    private long sourceDeviceId_;
    /**
     * <code>optional int64 source_device_id = 1;</code>
     *
     * <pre>
     * The device that generated this event.
     * If unset then the event was generated by the local device.
     * This field will always be set when the event is being sent between devices.
     * </pre>
     */
    public boolean hasSourceDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 source_device_id = 1;</code>
     *
     * <pre>
     * The device that generated this event.
     * If unset then the event was generated by the local device.
     * This field will always be set when the event is being sent between devices.
     * </pre>
     */
    public long getSourceDeviceId() {
      return sourceDeviceId_;
    }

    public static final int TARGET_DEVICE_ID_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Long> targetDeviceId_;
    /**
     * <code>repeated int64 target_device_id = 2;</code>
     *
     * <pre>
     * Zero or more devices that this event is targeted to.
     * If none specified, then it's meant for all devices that receive it.
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getTargetDeviceIdList() {
      return targetDeviceId_;
    }
    /**
     * <code>repeated int64 target_device_id = 2;</code>
     *
     * <pre>
     * Zero or more devices that this event is targeted to.
     * If none specified, then it's meant for all devices that receive it.
     * </pre>
     */
    public int getTargetDeviceIdCount() {
      return targetDeviceId_.size();
    }
    /**
     * <code>repeated int64 target_device_id = 2;</code>
     *
     * <pre>
     * Zero or more devices that this event is targeted to.
     * If none specified, then it's meant for all devices that receive it.
     * </pre>
     */
    public long getTargetDeviceId(int index) {
      return targetDeviceId_.get(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     * When the event happened, in milliseconds since the epoch, UTC.
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     *
     * <pre>
     * When the event happened, in milliseconds since the epoch, UTC.
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private org.damazio.notifier.protocol.Common.Event.Type type_;
    /**
     * <code>required .org.damazio.notifier.protocol.Event.Type type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .org.damazio.notifier.protocol.Event.Type type = 4;</code>
     */
    public org.damazio.notifier.protocol.Common.Event.Type getType() {
      return type_;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>optional bytes payload = 5;</code>
     *
     * <pre>
     * Payload is the type-dependent encoded protocol buffer payload.
     * A missing payload happens if no details were available about the event.
     * </pre>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes payload = 5;</code>
     *
     * <pre>
     * Payload is the type-dependent encoded protocol buffer payload.
     * A missing payload happens if no details were available about the event.
     * </pre>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private void initFields() {
      sourceDeviceId_ = 0L;
      targetDeviceId_ = java.util.Collections.emptyList();
      timestamp_ = 0L;
      type_ = org.damazio.notifier.protocol.Common.Event.Type.NOTIFICATION_RING;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, sourceDeviceId_);
      }
      for (int i = 0; i < targetDeviceId_.size(); i++) {
        output.writeInt64(2, targetDeviceId_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(4, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, payload_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sourceDeviceId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < targetDeviceId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(targetDeviceId_.get(i));
        }
        size += dataSize;
        size += 1 * getTargetDeviceIdList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, payload_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.damazio.notifier.protocol.Common.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.damazio.notifier.protocol.Common.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.damazio.notifier.protocol.Common.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.damazio.notifier.protocol.Common.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.damazio.notifier.protocol.Common.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.damazio.notifier.protocol.Common.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.damazio.notifier.protocol.Common.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.damazio.notifier.protocol.Common.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.damazio.notifier.protocol.Common.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.damazio.notifier.protocol.Common.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.damazio.notifier.protocol.Common.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code org.damazio.notifier.protocol.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.damazio.notifier.protocol.Common.Event, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:org.damazio.notifier.protocol.Event)
        org.damazio.notifier.protocol.Common.EventOrBuilder {
      // Construct using org.damazio.notifier.protocol.Common.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sourceDeviceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        targetDeviceId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = org.damazio.notifier.protocol.Common.Event.Type.NOTIFICATION_RING;
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public org.damazio.notifier.protocol.Common.Event getDefaultInstanceForType() {
        return org.damazio.notifier.protocol.Common.Event.getDefaultInstance();
      }

      public org.damazio.notifier.protocol.Common.Event build() {
        org.damazio.notifier.protocol.Common.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.damazio.notifier.protocol.Common.Event buildPartial() {
        org.damazio.notifier.protocol.Common.Event result = new org.damazio.notifier.protocol.Common.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sourceDeviceId_ = sourceDeviceId_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          targetDeviceId_ = java.util.Collections.unmodifiableList(targetDeviceId_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.targetDeviceId_ = targetDeviceId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(org.damazio.notifier.protocol.Common.Event other) {
        if (other == org.damazio.notifier.protocol.Common.Event.getDefaultInstance()) return this;
        if (other.hasSourceDeviceId()) {
          setSourceDeviceId(other.getSourceDeviceId());
        }
        if (!other.targetDeviceId_.isEmpty()) {
          if (targetDeviceId_.isEmpty()) {
            targetDeviceId_ = other.targetDeviceId_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTargetDeviceIdIsMutable();
            targetDeviceId_.addAll(other.targetDeviceId_);
          }
          
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.damazio.notifier.protocol.Common.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.damazio.notifier.protocol.Common.Event) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long sourceDeviceId_ ;
      /**
       * <code>optional int64 source_device_id = 1;</code>
       *
       * <pre>
       * The device that generated this event.
       * If unset then the event was generated by the local device.
       * This field will always be set when the event is being sent between devices.
       * </pre>
       */
      public boolean hasSourceDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 source_device_id = 1;</code>
       *
       * <pre>
       * The device that generated this event.
       * If unset then the event was generated by the local device.
       * This field will always be set when the event is being sent between devices.
       * </pre>
       */
      public long getSourceDeviceId() {
        return sourceDeviceId_;
      }
      /**
       * <code>optional int64 source_device_id = 1;</code>
       *
       * <pre>
       * The device that generated this event.
       * If unset then the event was generated by the local device.
       * This field will always be set when the event is being sent between devices.
       * </pre>
       */
      public Builder setSourceDeviceId(long value) {
        bitField0_ |= 0x00000001;
        sourceDeviceId_ = value;
        
        return this;
      }
      /**
       * <code>optional int64 source_device_id = 1;</code>
       *
       * <pre>
       * The device that generated this event.
       * If unset then the event was generated by the local device.
       * This field will always be set when the event is being sent between devices.
       * </pre>
       */
      public Builder clearSourceDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceDeviceId_ = 0L;
        
        return this;
      }

      private java.util.List<java.lang.Long> targetDeviceId_ = java.util.Collections.emptyList();
      private void ensureTargetDeviceIdIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          targetDeviceId_ = new java.util.ArrayList<java.lang.Long>(targetDeviceId_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int64 target_device_id = 2;</code>
       *
       * <pre>
       * Zero or more devices that this event is targeted to.
       * If none specified, then it's meant for all devices that receive it.
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getTargetDeviceIdList() {
        return java.util.Collections.unmodifiableList(targetDeviceId_);
      }
      /**
       * <code>repeated int64 target_device_id = 2;</code>
       *
       * <pre>
       * Zero or more devices that this event is targeted to.
       * If none specified, then it's meant for all devices that receive it.
       * </pre>
       */
      public int getTargetDeviceIdCount() {
        return targetDeviceId_.size();
      }
      /**
       * <code>repeated int64 target_device_id = 2;</code>
       *
       * <pre>
       * Zero or more devices that this event is targeted to.
       * If none specified, then it's meant for all devices that receive it.
       * </pre>
       */
      public long getTargetDeviceId(int index) {
        return targetDeviceId_.get(index);
      }
      /**
       * <code>repeated int64 target_device_id = 2;</code>
       *
       * <pre>
       * Zero or more devices that this event is targeted to.
       * If none specified, then it's meant for all devices that receive it.
       * </pre>
       */
      public Builder setTargetDeviceId(
          int index, long value) {
        ensureTargetDeviceIdIsMutable();
        targetDeviceId_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated int64 target_device_id = 2;</code>
       *
       * <pre>
       * Zero or more devices that this event is targeted to.
       * If none specified, then it's meant for all devices that receive it.
       * </pre>
       */
      public Builder addTargetDeviceId(long value) {
        ensureTargetDeviceIdIsMutable();
        targetDeviceId_.add(value);
        
        return this;
      }
      /**
       * <code>repeated int64 target_device_id = 2;</code>
       *
       * <pre>
       * Zero or more devices that this event is targeted to.
       * If none specified, then it's meant for all devices that receive it.
       * </pre>
       */
      public Builder addAllTargetDeviceId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureTargetDeviceIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, targetDeviceId_);
        
        return this;
      }
      /**
       * <code>repeated int64 target_device_id = 2;</code>
       *
       * <pre>
       * Zero or more devices that this event is targeted to.
       * If none specified, then it's meant for all devices that receive it.
       * </pre>
       */
      public Builder clearTargetDeviceId() {
        targetDeviceId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       * When the event happened, in milliseconds since the epoch, UTC.
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       * When the event happened, in milliseconds since the epoch, UTC.
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       * When the event happened, in milliseconds since the epoch, UTC.
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        
        return this;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       *
       * <pre>
       * When the event happened, in milliseconds since the epoch, UTC.
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        
        return this;
      }

      private org.damazio.notifier.protocol.Common.Event.Type type_ = org.damazio.notifier.protocol.Common.Event.Type.NOTIFICATION_RING;
      /**
       * <code>required .org.damazio.notifier.protocol.Event.Type type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .org.damazio.notifier.protocol.Event.Type type = 4;</code>
       */
      public org.damazio.notifier.protocol.Common.Event.Type getType() {
        return type_;
      }
      /**
       * <code>required .org.damazio.notifier.protocol.Event.Type type = 4;</code>
       */
      public Builder setType(org.damazio.notifier.protocol.Common.Event.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        
        return this;
      }
      /**
       * <code>required .org.damazio.notifier.protocol.Event.Type type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = org.damazio.notifier.protocol.Common.Event.Type.NOTIFICATION_RING;
        
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes payload = 5;</code>
       *
       * <pre>
       * Payload is the type-dependent encoded protocol buffer payload.
       * A missing payload happens if no details were available about the event.
       * </pre>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes payload = 5;</code>
       *
       * <pre>
       * Payload is the type-dependent encoded protocol buffer payload.
       * A missing payload happens if no details were available about the event.
       * </pre>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>optional bytes payload = 5;</code>
       *
       * <pre>
       * Payload is the type-dependent encoded protocol buffer payload.
       * A missing payload happens if no details were available about the event.
       * </pre>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        payload_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes payload = 5;</code>
       *
       * <pre>
       * Payload is the type-dependent encoded protocol buffer payload.
       * A missing payload happens if no details were available about the event.
       * </pre>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000010);
        payload_ = getDefaultInstance().getPayload();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.damazio.notifier.protocol.Event)
    }

    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.damazio.notifier.protocol.Event)
  }

  public interface PhoneNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.damazio.notifier.protocol.PhoneNumber)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string number = 1;</code>
     */
    boolean hasNumber();
    /**
     * <code>optional string number = 1;</code>
     */
    java.lang.String getNumber();
    /**
     * <code>optional string number = 1;</code>
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>optional string number_type = 2;</code>
     */
    boolean hasNumberType();
    /**
     * <code>optional string number_type = 2;</code>
     */
    java.lang.String getNumberType();
    /**
     * <code>optional string number_type = 2;</code>
     */
    com.google.protobuf.ByteString
        getNumberTypeBytes();

    /**
     * <code>optional string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional bytes picture = 4;</code>
     */
    boolean hasPicture();
    /**
     * <code>optional bytes picture = 4;</code>
     */
    com.google.protobuf.ByteString getPicture();
  }
  /**
   * Protobuf type {@code org.damazio.notifier.protocol.PhoneNumber}
   *
   * <pre>
   * General descriptor for a phone number.
   * </pre>
   */
  public static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:org.damazio.notifier.protocol.PhoneNumber)
      PhoneNumberOrBuilder {
    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PhoneNumber(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final PhoneNumber defaultInstance;
    public static PhoneNumber getDefaultInstance() {
      return defaultInstance;
    }

    public PhoneNumber getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private PhoneNumber(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              number_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              numberType_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              picture_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<PhoneNumber> PARSER =
        new com.google.protobuf.AbstractParser<PhoneNumber>() {
      public PhoneNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneNumber(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NUMBER_FIELD_NUMBER = 1;
    private java.lang.Object number_;
    /**
     * <code>optional string number = 1;</code>
     */
    public boolean hasNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string number = 1;</code>
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          number_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string number = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBER_TYPE_FIELD_NUMBER = 2;
    private java.lang.Object numberType_;
    /**
     * <code>optional string number_type = 2;</code>
     */
    public boolean hasNumberType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string number_type = 2;</code>
     */
    public java.lang.String getNumberType() {
      java.lang.Object ref = numberType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          numberType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string number_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNumberTypeBytes() {
      java.lang.Object ref = numberType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        numberType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PICTURE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString picture_;
    /**
     * <code>optional bytes picture = 4;</code>
     */
    public boolean hasPicture() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes picture = 4;</code>
     */
    public com.google.protobuf.ByteString getPicture() {
      return picture_;
    }

    private void initFields() {
      number_ = "";
      numberType_ = "";
      name_ = "";
      picture_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNumberTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, picture_);
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNumberBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNumberTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, picture_);
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.damazio.notifier.protocol.Common.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.damazio.notifier.protocol.Common.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.damazio.notifier.protocol.Common.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.damazio.notifier.protocol.Common.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.damazio.notifier.protocol.Common.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.damazio.notifier.protocol.Common.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.damazio.notifier.protocol.Common.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.damazio.notifier.protocol.Common.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.damazio.notifier.protocol.Common.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.damazio.notifier.protocol.Common.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.damazio.notifier.protocol.Common.PhoneNumber prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code org.damazio.notifier.protocol.PhoneNumber}
     *
     * <pre>
     * General descriptor for a phone number.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.damazio.notifier.protocol.Common.PhoneNumber, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:org.damazio.notifier.protocol.PhoneNumber)
        org.damazio.notifier.protocol.Common.PhoneNumberOrBuilder {
      // Construct using org.damazio.notifier.protocol.Common.PhoneNumber.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        number_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        numberType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        picture_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public org.damazio.notifier.protocol.Common.PhoneNumber getDefaultInstanceForType() {
        return org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance();
      }

      public org.damazio.notifier.protocol.Common.PhoneNumber build() {
        org.damazio.notifier.protocol.Common.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.damazio.notifier.protocol.Common.PhoneNumber buildPartial() {
        org.damazio.notifier.protocol.Common.PhoneNumber result = new org.damazio.notifier.protocol.Common.PhoneNumber(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.number_ = number_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.numberType_ = numberType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.picture_ = picture_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(org.damazio.notifier.protocol.Common.PhoneNumber other) {
        if (other == org.damazio.notifier.protocol.Common.PhoneNumber.getDefaultInstance()) return this;
        if (other.hasNumber()) {
          bitField0_ |= 0x00000001;
          number_ = other.number_;
          
        }
        if (other.hasNumberType()) {
          bitField0_ |= 0x00000002;
          numberType_ = other.numberType_;
          
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          
        }
        if (other.hasPicture()) {
          setPicture(other.getPicture());
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.damazio.notifier.protocol.Common.PhoneNumber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.damazio.notifier.protocol.Common.PhoneNumber) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object number_ = "";
      /**
       * <code>optional string number = 1;</code>
       */
      public boolean hasNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string number = 1;</code>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            number_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        number_ = value;
        
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        number_ = getDefaultInstance().getNumber();
        
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        number_ = value;
        
        return this;
      }

      private java.lang.Object numberType_ = "";
      /**
       * <code>optional string number_type = 2;</code>
       */
      public boolean hasNumberType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string number_type = 2;</code>
       */
      public java.lang.String getNumberType() {
        java.lang.Object ref = numberType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            numberType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string number_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNumberTypeBytes() {
        java.lang.Object ref = numberType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          numberType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string number_type = 2;</code>
       */
      public Builder setNumberType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        numberType_ = value;
        
        return this;
      }
      /**
       * <code>optional string number_type = 2;</code>
       */
      public Builder clearNumberType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numberType_ = getDefaultInstance().getNumberType();
        
        return this;
      }
      /**
       * <code>optional string number_type = 2;</code>
       */
      public Builder setNumberTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        numberType_ = value;
        
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        
        return this;
      }

      private com.google.protobuf.ByteString picture_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes picture = 4;</code>
       */
      public boolean hasPicture() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes picture = 4;</code>
       */
      public com.google.protobuf.ByteString getPicture() {
        return picture_;
      }
      /**
       * <code>optional bytes picture = 4;</code>
       */
      public Builder setPicture(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        picture_ = value;
        
        return this;
      }
      /**
       * <code>optional bytes picture = 4;</code>
       */
      public Builder clearPicture() {
        bitField0_ = (bitField0_ & ~0x00000008);
        picture_ = getDefaultInstance().getPicture();
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.damazio.notifier.protocol.PhoneNumber)
    }

    static {
      defaultInstance = new PhoneNumber(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.damazio.notifier.protocol.PhoneNumber)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
